# Generated by Django 3.2.3 on 2021-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='nickname',
            field=models.CharField(default='link', max_length=20),
        ),
    ]
